<%@ Page Language="C#" MasterPageFile="~/Site.Master" Title="DocIO" AutoEventWireup="true" CodeBehind="DocIOFeatures.aspx.cs" Inherits="SyncfusionASPNETApplication20.DocIOFeatures" %>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
<h2>DocIO Features:</h2>
<br />
<li> DocIO Samples - Getting Started</li>
<br/>
<div id = "ControlRegion">
    <style>
        label {
        display: inline;     
    }
    input, textarea {       
        width: auto;
    }
    </style>
<div>
             <p>
    This sample illustrates to create a Word document with text, image and table, using few lines of code with Essential DocIO.</p>
    <br />
    <p> 
        Click the button below to view the Word document generated by Essential DocIO. Please note that MS Word Viewer or MS Word is required to view the resultant document.
    </p>
    <div>
        <table width="650px" id="PanelTable" cellspacing="0" cellpadding="0" border="0">
            <tr>
                <td>
                    <br />
                    <div>
                        <table width="100%">
                            <tr>
                                <td valign="middle" align="left">
                                    <asp:Label Width="65px" runat="server" ID="label1" Text="Save As :"></asp:Label>
                                    <asp:RadioButton ID="rdButtonWord97To2003" runat="server" GroupName="Group1" Text="Word 97-2003" />
                                    <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWord2007" runat="server" GroupName="Group1"
                                        Text="Word 2007" />
                                    <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWord2010" runat="server" GroupName="Group1"
                                        Text="Word 2010" />
                                        <asp:RadioButton Style="margin-left: 5px" ID="rdButtonWord2013" runat="server" GroupName="Group1"
                                        Text="Word 2013" Checked="True" />
                                </td>
                            </tr>
							<tr>
                                <td height="10px">
                                </td>
                            </tr>
                            <tr>
                                <td align="left">
                                    <asp:Button Width="150px" ID="Button1" Height="27px" runat="server" OnClick="Button1_Click"
                                        Text="Generate Document" />
                                </td>
                            </tr>
                            <tr>
                                <td height="10px">
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</div>
</div>
</asp:Content>
